# Rename this file to languages.toml to enable multilingual support
[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "yuna0x0's Blog"
weight = 1

# [en]
# languageName = "English"
# languagedirection = "ltr"
# title = "yuna0x0's Blog"
# weight = 2
